---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: CentOS
    image: quay.io/centos/centos:stream8
    pre_build_image: true
  - name: Alpine
    image: test:latest
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
